In [14]:
import numpy as np
a=np.array([[2,13,6],[22,3,5],[7,8,16]])
b=np.array([[15,8,7],[6,16,20],[3,2,1]])


In [15]:
print("MATRIX ADDITION\n",a+b)

MATRIX ADDITION
 [[17 21 13]
 [28 19 25]
 [10 10 17]]


In [16]:
print("MATRIX SUBSTRACTION\n",a-b)

MATRIX SUBSTRACTION
 [[-13   5  -1]
 [ 16 -13 -15]
 [  4   6  15]]


In [17]:
print("MATRIX MULTIPLICATION\n",a@b)

MATRIX MULTIPLICATION
 [[126 236 280]
 [363 234 219]
 [201 216 225]]


In [18]:
print("ELEMENT WISE MULTIPLICATION\n",a*b)

ELEMENT WISE MULTIPLICATION
 [[ 30 104  42]
 [132  48 100]
 [ 21  16  16]]


In [19]:
print("DETERMINANT OF A\n",np.linalg.det(a))

DETERMINANT OF A
 -3175.0000000000005


In [20]:
print("INVERSE OF A\n",np.linalg.inv(a))

INVERSE OF A
 [[-0.00251969  0.0503937  -0.01480315]
 [ 0.09984252  0.00314961 -0.0384252 ]
 [-0.0488189  -0.02362205  0.08818898]]


In [21]:
print("EIGEN VALUES AND EIGEN VECTORS\n",np.linalg.eig(a))

EIGEN VALUES AND EIGEN VECTORS
 EigResult(eigenvalues=array([-14.28829943,  27.08375937,   8.20454006]), eigenvectors=array([[-0.60666973,  0.45570907, -0.30398743],
       [ 0.79195648,  0.55993628, -0.51499815],
       [-0.06896933,  0.69195419,  0.80147897]]))


In [22]:
print("MAXIMUM OF A\n",np.max(a))
print("MAXIMUM OF B\n",np.max(b))

MAXIMUM OF A
 22
MAXIMUM OF B
 20


In [23]:
print("STANDARD VARIATION OF A\n",np.std(a))

STANDARD VARIATION OF A
 6.226189211609734
